apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: military-chicken-python 
  janus-idp.io/tekton: military-chicken-python
  backstage.io/kubernetes-id: military-chicken-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: military-chicken-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  