apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: military-chicken-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: military-chicken-python 
  name: military-chicken-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: military-chicken-python 
